// Interface automatically generated by schemas-to-ts

import { Question } from '../../../../components/faq/interfaces/Question';
import { Question_Plain } from '../../../../components/faq/interfaces/Question';
import { Question_NoRelations } from '../../../../components/faq/interfaces/Question';

export interface Faq {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    questions: Question[];
  };
}
export interface Faq_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  questions: Question_Plain[];
}

export interface Faq_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  questions: Question_NoRelations[];
}

export interface Faq_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  questions: Question_Plain[];
}
