// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface Size {
  value?: string;
  file?: { data: Media };
}
export interface Size_Plain {
  value?: string;
  file?: Media;
}

export interface Size_NoRelations {
  value?: string;
  file?: number;
}

