// Interface automatically generated by schemas-to-ts

import { User } from '../../../../common/schemas-to-ts/User';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Status {
  PendingPayment = 'pending_payment',
  PaymentError = 'payment_error',
  Paid = 'paid',
  Cancelled = 'cancelled',}

export interface Order {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    note?: string;
    status?: Status;
    products?: any;
    user?: { data: User };
    uuid?: any;
    price?: string;
  };
}
export interface Order_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  note?: string;
  status?: Status;
  products?: any;
  user?: User_Plain;
  uuid?: any;
  price?: string;
}

export interface Order_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  note?: string;
  status?: Status;
  products?: any;
  user?: number;
  uuid?: any;
  price?: string;
}

export interface Order_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  note?: string;
  status?: Status;
  products?: any;
  user?: AdminPanelRelationPropertyModification<User_Plain>;
  uuid?: any;
  price?: string;
}
