// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { PageCategory } from '../../../page-category/content-types/page-category/page-category';
import { PageCategory_Plain } from '../../../page-category/content-types/page-category/page-category';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Page {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    content?: any;
    thumbnail?: { data: Media };
    page_category?: { data: PageCategory };
    slug?: string;
    locale: string;
    localizations?: { data: Page[] };
  };
}
export interface Page_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  content?: any;
  thumbnail?: Media;
  page_category?: PageCategory_Plain;
  slug?: string;
  locale: string;
  localizations?: Page[];
}

export interface Page_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  content?: any;
  thumbnail?: number;
  page_category?: number;
  slug?: string;
  locale: string;
  localizations?: Page[];
}

export interface Page_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  content?: any;
  thumbnail?: AdminPanelRelationPropertyModification<Media>;
  page_category?: AdminPanelRelationPropertyModification<PageCategory_Plain>;
  slug?: string;
  locale: string;
  localizations?: Page[];
}
