// Interface automatically generated by schemas-to-ts

export interface PageCategory {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    locale: string;
    localizations?: { data: PageCategory[] };
  };
}
export interface PageCategory_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  locale: string;
  localizations?: PageCategory[];
}

export interface PageCategory_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  locale: string;
  localizations?: PageCategory[];
}

export interface PageCategory_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  locale: string;
  localizations?: PageCategory[];
}
