// Interface automatically generated by schemas-to-ts

import { CharacterItem } from './CharacterItem';
import { CharacterItem_Plain } from './CharacterItem';
import { CharacterItem_NoRelations } from './CharacterItem';

export interface CharacterList {
  characters: CharacterItem[];
}
export interface CharacterList_Plain {
  characters: CharacterItem_Plain[];
}

export interface CharacterList_NoRelations {
  characters: CharacterItem_NoRelations[];
}

