// Interface automatically generated by schemas-to-ts

export interface CharacterItem {
  width?: string;
  height?: string;
  code?: string;
  country?: string;
  color?: any;
}
export interface CharacterItem_Plain {
  width?: string;
  height?: string;
  code?: string;
  country?: string;
  color?: any;
}

export interface CharacterItem_NoRelations {
  width?: string;
  height?: string;
  code?: string;
  country?: string;
  color?: any;
}

