// Interface automatically generated by schemas-to-ts

export interface Property {
  name?: string;
  value?: string;
}
export interface Property_Plain {
  name?: string;
  value?: string;
}

export interface Property_NoRelations {
  name?: string;
  value?: string;
}

