// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Product } from '../../../product/content-types/product/product';
import { Product_Plain } from '../../../product/content-types/product/product';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Category {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    preview?: { data: Media };
    products: { data: Product[] };
    locale: string;
    localizations?: { data: Category[] };
  };
}
export interface Category_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  preview?: Media;
  products: Product_Plain[];
  locale: string;
  localizations?: Category[];
}

export interface Category_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  preview?: number;
  products: number[];
  locale: string;
  localizations?: Category[];
}

export interface Category_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  preview?: AdminPanelRelationPropertyModification<Media>;
  products: AdminPanelRelationPropertyModification<Product_Plain>;
  locale: string;
  localizations?: Category[];
}
