// Interface automatically generated by schemas-to-ts

export interface Question {
  question?: string;
  answer?: any;
}
export interface Question_Plain {
  question?: string;
  answer?: any;
}

export interface Question_NoRelations {
  question?: string;
  answer?: any;
}

