// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Category } from '../../../category/content-types/category/category';
import { Property } from '../../../../components/item/interfaces/Property';
import { Category_Plain } from '../../../category/content-types/category/category';
import { Property_Plain } from '../../../../components/item/interfaces/Property';
import { Property_NoRelations } from '../../../../components/item/interfaces/Property';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    description?: any;
    thumbnails?: { data: Media[] };
    price?: string;
    category?: { data: Category };
    attribute: Property[];
    comments?: any;
    slug?: string;
    viewed?: number;
    file?: { data: Media };
    locale: string;
    localizations?: { data: Product[] };
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: any;
  thumbnails?: Media[];
  price?: string;
  category?: Category_Plain;
  attribute: Property_Plain[];
  comments?: any;
  slug?: string;
  viewed?: number;
  file?: Media;
  locale: string;
  localizations?: Product[];
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: any;
  thumbnails?: number[];
  price?: string;
  category?: number;
  attribute: Property_NoRelations[];
  comments?: any;
  slug?: string;
  viewed?: number;
  file?: number;
  locale: string;
  localizations?: Product[];
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: any;
  thumbnails?: AdminPanelRelationPropertyModification<Media>[];
  price?: string;
  category?: AdminPanelRelationPropertyModification<Category_Plain>;
  attribute: Property_Plain[];
  comments?: any;
  slug?: string;
  viewed?: number;
  file?: AdminPanelRelationPropertyModification<Media>;
  locale: string;
  localizations?: Product[];
}
