// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Category } from '../../../category/content-types/category/category';
import { CharacterItem } from '../../../../components/list/interfaces/CharacterItem';
import { Category_Plain } from '../../../category/content-types/category/category';
import { CharacterItem_Plain } from '../../../../components/list/interfaces/CharacterItem';
import { CharacterItem_NoRelations } from '../../../../components/list/interfaces/CharacterItem';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    description?: any;
    thumbnails?: { data: Media[] };
    price?: string;
    category?: { data: Category };
    slug?: any;
    properties?: CharacterItem;
    text?: string;
    locale: string;
    localizations?: { data: Product[] };
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: any;
  thumbnails?: Media[];
  price?: string;
  category?: Category_Plain;
  slug?: any;
  properties?: CharacterItem_Plain;
  text?: string;
  locale: string;
  localizations?: Product[];
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: any;
  thumbnails?: number[];
  price?: string;
  category?: number;
  slug?: any;
  properties?: CharacterItem_NoRelations;
  text?: string;
  locale: string;
  localizations?: Product[];
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: any;
  thumbnails?: AdminPanelRelationPropertyModification<Media>[];
  price?: string;
  category?: AdminPanelRelationPropertyModification<Category_Plain>;
  slug?: any;
  properties?: CharacterItem_Plain;
  text?: string;
  locale: string;
  localizations?: Product[];
}
