// Interface automatically generated by schemas-to-ts

export interface Attribute {
  name?: string;
  value?: string;
}
export interface Attribute_Plain {
  name?: string;
  value?: string;
}

export interface Attribute_NoRelations {
  name?: string;
  value?: string;
}

