// Interface automatically generated by schemas-to-ts

export enum Name {
  Color = 'color',
  Weight = 'weight',
  Height = 'height',
  Size = 'size',}

export interface Property {
  name?: Name;
  value?: string;
}
export interface Property_Plain {
  name?: Name;
  value?: string;
}

export interface Property_NoRelations {
  name?: Name;
  value?: string;
}

